### ISSUE TITLE
I got an error.

### ISSUE THREAD

**Issue by Sealington** [1j01/textual-paint#7]
So, I ran the command, and I got this:
```
Traceback (most recent call last):
  File "/home/sealington33/.local/bin/textual-paint", line 5, in <module>
    from textual_paint.paint import main
  File "/home/sealington33/.local/lib/python3.9/site-packages/textual_paint/paint.py", line 35, in <module>
    from textual_paint.action import Action
  File "/home/sealington33/.local/lib/python3.9/site-packages/textual_paint/action.py", line 5, in <module>
    from textual_paint.ansi_art_document import AnsiArtDocument
  File "/home/sealington33/.local/lib/python3.9/site-packages/textual_paint/ansi_art_document.py", line 583
    match instruction.region:
          ^
SyntaxError: invalid syntax
```

**Comment by 1j01** [comment]
You'll need Python 3.10 or later. You can check what version you have with `python --version`
